import { isSafeInternalPath } from './safe-path';

/**
 * Referral landing rules (task 2.4, `/r/{code}`).
 *
 * Pure: what counts as a referral code, and where a referral link may send someone. Both are
 * untrusted input arriving from a link somebody else wrote, so both are decided here and tested
 * directly rather than inside a route handler.
 */

/**
 * A referral code is a short, opaque token. Codes are generated by window 17, not typed by us, so
 * this is a shape check rather than a lookup: anything that could confuse a cookie, a log line or a
 * downstream report is refused before it is stored.
 *
 * Deliberately narrow — letters, digits, `-` and `_`, 4 to 64 characters. No dots (which invite
 * confusion with a file extension in the middleware matcher), no slashes, no whitespace.
 */
const CODE = /^[A-Za-z0-9_-]{4,64}$/;

export function isReferralCode(value: string | undefined | null): value is string {
  return typeof value === 'string' && CODE.test(value);
}

/**
 * Where `/r/{code}?to=…` may redirect: a **path on this site**, never another origin.
 *
 * A referral link is shared publicly and clicked without inspection, so an open redirect here lets
 * anyone borrow the brand's domain to launder a link to their own. The rule about what a safe path
 * is lives in `isSafeInternalPath` — shared with sign-in's `returnTo`, because it was duplicated and
 * the duplicate is what shipped a control-character bypass. The route also checks the resolved
 * origin before redirecting.
 */
export function safeReferralTarget(value: string | null | undefined, fallback = '/'): string {
  if (!isSafeInternalPath(value)) return fallback;
  // A referral that lands on another referral would re-enter this handler on every hop.
  if (value === '/r' || value.startsWith('/r/')) return fallback;
  return value;
}
