/**
 * Referral landing rules (task 2.4, `/r/{code}`).
 *
 * Pure: what counts as a referral code, and where a referral link may send someone. Both are
 * untrusted input arriving from a link somebody else wrote, so both are decided here and tested
 * directly rather than inside a route handler.
 */

/**
 * A referral code is a short, opaque token. Codes are generated by window 17, not typed by us, so
 * this is a shape check rather than a lookup: anything that could confuse a cookie, a log line or a
 * downstream report is refused before it is stored.
 *
 * Deliberately narrow — letters, digits, `-` and `_`, 4 to 64 characters. No dots (which invite
 * confusion with a file extension in the middleware matcher), no slashes, no whitespace.
 */
const CODE = /^[A-Za-z0-9_-]{4,64}$/;

export function isReferralCode(value: string | undefined | null): value is string {
  return typeof value === 'string' && CODE.test(value);
}

/**
 * Where `/r/{code}?to=…` may redirect: a **path on this site**, never another origin.
 *
 * A referral link is shared publicly and clicked without inspection, so an open redirect here would
 * let anyone borrow the brand's domain to launder a link to their own. Same rule as sign-in's
 * `returnTo`, restated rather than imported, because this one also has to reject a path that would
 * bounce the visitor straight back into `/r/` and loop.
 */
export function safeReferralTarget(value: string | null | undefined, fallback = '/'): string {
  if (typeof value !== 'string' || value === '') return fallback;
  if (!value.startsWith('/')) return fallback;
  // `//evil.example` is protocol-relative: the browser reads it as another origin.
  if (value.startsWith('//') || value.startsWith('/\\')) return fallback;
  if (value.includes('\\')) return fallback;
  // A referral that lands on another referral would re-enter this handler on every hop.
  if (value === '/r' || value.startsWith('/r/')) return fallback;
  return value;
}
