// Generates src/generated/{schemas.ts,types.ts} from schemas/**/v<N>.json.
// schemas.ts inlines every schema (no fs at runtime); types.ts holds one interface per event version.
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const SCHEMAS = resolve(here, '../schemas');
const OUT = resolve(here, '../src/generated');

const pascal = (s) => s.replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c) => c.toUpperCase());

const common = JSON.parse(readFileSync(join(SCHEMAS, 'common/v1.json'), 'utf8'));
const envelope = JSON.parse(readFileSync(join(SCHEMAS, 'envelope/v1.json'), 'utf8'));

/** Replace $ref to common/v1.json#/$defs/X with the definition itself (for the TS generator only). */
function inlineRefs(node) {
  if (Array.isArray(node)) return node.map(inlineRefs);
  if (node && typeof node === 'object') {
    if (typeof node.$ref === 'string') {
      const m = node.$ref.match(/common\/v1\.json#\/\$defs\/(\w+)$/);
      if (!m) throw new Error(`unsupported $ref ${node.$ref}`);
      const def = common.$defs[m[1]];
      if (!def) throw new Error(`unknown common def ${m[1]}`);
      return inlineRefs({ ...def, tsType: m[1] === 'uuid' ? 'string' : undefined });
    }
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = inlineRefs(v);
    return out;
  }
  return node;
}

const topics = readdirSync(SCHEMAS, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name.includes('.'))
  .map((d) => d.name)
  .sort();

const entries = [];
for (const topic of topics) {
  const versions = readdirSync(join(SCHEMAS, topic))
    .map((f) => f.match(/^v(\d+)\.json$/)?.[1])
    .filter(Boolean)
    .map(Number)
    .sort((a, b) => a - b);
  for (const version of versions) {
    const schema = JSON.parse(readFileSync(join(SCHEMAS, topic, `v${version}.json`), 'utf8'));
    entries.push({ topic, version, name: `${pascal(topic)}V${version}`, schema });
  }
}

// ---- schemas.ts ----
const schemasTs = [
  '// GENERATED by scripts/generate.mjs — do not edit. Source: packages/events/schemas/**',
  '/* eslint-disable */',
  `export const COMMON_SCHEMA = ${JSON.stringify(common)} as const;`,
  `export const ENVELOPE_SCHEMA = ${JSON.stringify(envelope)} as const;`,
  `export const EVENT_SCHEMAS = ${JSON.stringify(
    Object.fromEntries(entries.map((e) => [`${e.topic}@${e.version}`, e.schema])),
  )} as const;`,
  `export const EVENT_TOPICS = ${JSON.stringify(topics)} as const;`,
  `export const LATEST_VERSION = ${JSON.stringify(
    Object.fromEntries(
      topics.map((t) => [
        t,
        Math.max(...entries.filter((e) => e.topic === t).map((e) => e.version)),
      ]),
    ),
  )} as const;`,
  '',
].join('\n');

// ---- types.ts ----
const opts = {
  bannerComment: '',
  additionalProperties: false,
  strictIndexSignatures: true,
  format: false,
};
let typesTs =
  '// GENERATED by scripts/generate.mjs — do not edit. Source: packages/events/schemas/**\n/* eslint-disable */\n';
const env = inlineRefs(envelope);
env.title = 'EventEnvelopeV1Base';
typesTs += await compile(env, 'EventEnvelopeV1Base', opts);
for (const e of entries) {
  const s = inlineRefs(e.schema);
  s.title = e.name;
  typesTs += await compile(s, e.name, opts);
}
typesTs += `\nexport interface EventPayloads {\n${entries
  .map((e) => `  '${e.topic}@${e.version}': ${e.name};`)
  .join('\n')}\n}\n`;
typesTs += `\nexport interface LatestPayloads {\n${topics
  .map((t) => {
    const latest = entries.filter((e) => e.topic === t).sort((a, b) => b.version - a.version)[0];
    return `  '${t}': ${latest.name};`;
  })
  .join('\n')}\n}\n`;

mkdirSync(OUT, { recursive: true });
const write = (file, content) => {
  const p = join(OUT, file);
  if (existsSync(p) && readFileSync(p, 'utf8') === content) return;
  writeFileSync(p, content);
};
write('schemas.ts', schemasTs);
write('types.ts', typesTs);
console.log(`events: generated ${entries.length} event types across ${topics.length} topics`);
