#!/usr/bin/env bash
# Usage: bash scripts/merge-queue.sh "<pr> <branch>" ["<pr> <branch>" ...]   e.g. "98 infra/phase2"
# Manager-only. For each PR: merge origin/main into a detached checkout of the branch (lockfile
# regenerated on conflict), push HEAD:refs/heads/<branch> (never the local ref — the window owns it),
# wait for CI ignoring the advisory images check, merge with a merge commit. Refuses on red CI.
# Manager merge queue: for each PR, merge origin/main into the branch (lockfile regenerated), push, merge PR.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$ROOT/../wt-mgr-tmp"
cd "$ROOT"
for spec in "$@"; do
  set -- $spec; PR=$1; BR=$2
  echo "=== PR #$PR ($BR) ==="
  git fetch -q origin
  rm -rf "$TMP"; git worktree prune
  git worktree add -q "$TMP" "origin/$BR" --detach || { echo "worktree failed"; continue; }
  (
    cd "$TMP" || exit 1
    # stay detached at origin/$BR: the window's worktree owns the local branch ref
    if ! git merge --no-edit origin/main >/dev/null 2>&1; then
      conflicts="$(git diff --name-only --diff-filter=U)"
      if [ "$conflicts" != "pnpm-lock.yaml" ]; then echo "non-lockfile conflicts: $conflicts"; git merge --abort; exit 1; fi
      git checkout --theirs pnpm-lock.yaml
      pnpm install --lockfile-only >/dev/null 2>&1 || { echo "pnpm install failed"; git merge --abort; exit 1; }
      git add pnpm-lock.yaml
      git -c core.editor=true commit -q -m "merge main into $BR (lockfile regenerated by manager)" || { echo "commit failed"; exit 1; }
    fi
    pnpm install --frozen-lockfile >/dev/null 2>&1 || { echo "frozen-lockfile check failed"; exit 1; }
    git push -q origin "HEAD:refs/heads/$BR" && echo "pushed $BR"
  ) || { echo "skipping #$PR"; git worktree remove --force "$TMP" 2>/dev/null; continue; }
  git worktree remove --force "$TMP" 2>/dev/null
  # wait for CI, then merge
  for i in $(seq 1 40); do
    # ignore the advisory "app images" check (issue #59) when deciding
    st="$(gh pr view "$PR" --json mergeStateStatus,statusCheckRollup --jq '"\(.mergeStateStatus) \((.statusCheckRollup // []) | map(select((.name // .context // "") | test("app images") | not)) | map(.conclusion // .status) | unique | join(","))"')"
    case "$st" in
      *FAILURE*) echo "CI failed on #$PR: $st"; break;;
      "CLEAN SUCCESS"*|"UNSTABLE SUCCESS"*|"CLEAN "*) break;;
    esac
    sleep 15
  done
  echo "state: $st"
  case "$st" in *FAILURE*|*PENDING*|*IN_PROGRESS*|*QUEUED*) echo "NOT merging #$PR (CI not green)"; continue;; esac
  if gh pr merge "$PR" --merge --delete-branch=false >/dev/null 2>&1; then echo "merged #$PR"; else echo "MERGE FAILED #$PR"; fi
done
cd "$ROOT" && git pull -q --ff-only origin main && git log --oneline -8 | cat
